export default {
    GET_STATES: "GET_STATES",
    ADD_STATE: "ADD_STATE",
    UPDATE_STATE: "UPDATE_STATE",
    DELETE_STATE: "DELETE_STATE",

    GET_CITIES: "GET_CITIES",
    ADD_CITY: "ADD_CITY",
    UPDATE_CITY: "UPDATE_CITY",
    DELETE_CITY: "DELETE_CITY",

    GET_ZONES: "GET_ZONES",
    ADD_ZONE: "ADD_ZONE",
    UPDATE_ZONE: "UPDATE_ZONE",
    DELETE_ZONE: "DELETE_ZONE"
  };
  