export default {
  GET_STATES: "GET_STATES",
  ADD_STATE: "ADD_STATE",
  UPDATE_STATE: "UPDATE_STATE",
  DELETE_STATE: "DELETE_STATE",

  GET_CITIES: "GET_CITIES",
  ADD_CITY: "ADD_CITY",
  UPDATE_CITY: "UPDATE_CITY",
  DELETE_CITY: "DELETE_CITY",

  GET_ZONES: "GET_ZONES",
  ADD_ZONE: "ADD_ZONE",
  UPDATE_ZONE: "UPDATE_ZONE",
  DELETE_ZONE: "DELETE_ZONE",

  GET_DISTRICT: "GET_DISTRICT",
  ADD_OR_UPDATE_DISTRICT: "ADD_OR_UPDATE_DISTRICT",
  DELETE_DISTRICT: "DELETE_DISTRICT",

  GET_SUB_DISTRICT: "GET_SUB_DISTRICT",
  ADD_OR_UPDATE_SUB_DISTRICT: "ADD_OR_UPDATE_SUB_DISTRICT",
  DELETE_SUB_DISTRICT: "DELETE__DISTRICT",

  GET_LOCATION: "GET_LOCATION",
  ADD_OR_UPDATE_LOCATION: "ADD_OR_UPDATE_LOCATION",
  DELETE_LOCATION: "DELETE_LOCATION",

  GET_SUB_LOCATION: "GET_SUB_LOCATION",
  ADD_OR_UPDATE_SUB_LOCATION: "ADD_OR_UPDATE_SUB_LOCATION",
  DELETE_SUB_LOCATION: "DELETE_SUB_LOCATION",
};
