export default{
    LOG_IN: "LOG_IN",
    LOG_OUT: "lOG_OUT",
    FORGET_PASSWORD: "FORGET_PASSWORD",
    MATCH_OTP: "MATCH_OTP",
    RESET_FORGOT_PASSWORD: "RESET_FORGOT_PASSWORD",
    RESET_PASSWORD: "RESET_PASSWORD"
}