export default {
    ADD_PROPERTY_NETWORK_CALL: "ADD_PROPERTY_NETWORK_CALL",
    REMOVE_PROPERTY_NETWORK_CALL: "REMOVE_PROPERTY_NETWORK_CALL",
    ADD_TRACKS_LIST_NETWORK_CALL: "ADD_TRACKS_LIST_NETWORK_CALL"
};
